### ISSUE TITLE
USB drive not exposed

### ISSUE THREAD

**Issue by ADoozer** [Black-FX/RP2040_Mouse#1]
Hi Darren.

I have had a couple of these boards built and populated by PCBWay, but I'm struggling to load the uf2 file.
I have jumpered the USB_Boot and connected to my PC with a USB A - USB A (via the USB socket) but the drive does not expose.

Do I need to do anything with the RP2040 to allow it to expose the drive or should this work straight out of the box?

Regards
Dave

**Comment by Black-FX** [comment]
Hi.

You will need to bridge the resistor pads on the underside and solder a USB test points on the underside.

Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: ADoozer ***@***.***>
Sent: Friday, June 7, 2024 7:41:19 AM
To: Black-FX/RP2040_Mouse ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Black-FX/RP2040_Mouse] USB drive not exposed (Issue #1)


Hi Darren.

I have had a couple of these boards built and populated by PCBWay, but I'm struggling to load the uf2 file.
I have jumpered the USB_Boot and connected to my PC with a USB A - USB A (via the USB socket) but the drive does not expose.

Do I need to do anything with the RP2040 to allow it to expose the drive or should this work straight out of the box?

Regards
Dave

**Comment by ADoozer** [comment]
Thanks Darren.

I have it working now.


Couple of notes for others who may build the project...

The D+ and D- on the edge connector are swapped from a standard usb footprint.
I bought a cheap pogo pin edge connector from aliexpress and just switched the pins around

dont do this

![Dont do this](https://github.com/Black-FX/RP2040_Mouse/assets/50127357/f719573a-8207-41f1-bf6b-30650de05fbf)

do this

![do this](https://github.com/Black-FX/RP2040_Mouse/assets/50127357/ffb6b0de-d007-4b60-8d4d-4a0362fd5a04)

Regards
Dave
